

ZO_CreateStringId("SI_MAP_INFO_MODE_WAYSHRINES","Wayshrines")
ZO_CreateStringId("SI_MAP_INFO_MODE_PLAYERS","Players")

ZO_CreateStringId("SI_MAP_INFO_WAYSHRINES_CATEGORY_RECENT","Recent")
ZO_CreateStringId("SI_MAP_INFO_WAYSHRINES_CATEGORY_FAVOURITES","Favourites")
ZO_CreateStringId("SI_MAP_INFO_WAYSHRINES_CATEGORY_CURRENT","Zone")

ZO_CreateStringId("SI_MAP_INFO_PLAYERS_CATEGORY_FRIENDS","Friends")
ZO_CreateStringId("SI_MAP_INFO_PLAYERS_CATEGORY_GROUP","Group")
ZO_CreateStringId("SI_MAP_INFO_PLAYERS_CATEGORY_ZONE","Zone")
