

local Utils = FasterTravel.Utils

local Data = {}

-- Hardcoded lookup of all fast travel nodes in all zones =( But at least it is automatically generated by WayshrineDataGenerator =D

local _zoneNodeLookup = {
	[-2147483648] = 
	{
	},
	[353] = 
	{
		[1] = 
		{
			["poiIndex"] = 45,
			["nodeIndex"] = 217,
		},
		[2] = 
		{
			["poiIndex"] = 46,
			["nodeIndex"] = 219,
		},
		[3] = 
		{
			["poiIndex"] = 47,
			["nodeIndex"] = 218,
		},
		[4] = 
		{
			["poiIndex"] = 50,
			["nodeIndex"] = 220,
		},
		[5] = 
		{
			["poiIndex"] = 62,
			["nodeIndex"] = 229,
		},
		[6] = 
		{
			["poiIndex"] = 63,
			["nodeIndex"] = 225,
		},
		[7] = 
		{
			["poiIndex"] = 64,
			["nodeIndex"] = 226,
		},
		[8] = 
		{
			["poiIndex"] = 65,
			["nodeIndex"] = 227,
		},
		[9] = 
		{
			["poiIndex"] = 86,
			["nodeIndex"] = 233,
		},
		[10] = 
		{
			["poiIndex"] = 87,
			["nodeIndex"] = 234,
		},
		[11] = 
		{
			["poiIndex"] = 88,
			["nodeIndex"] = 235,
		},
	},
	[2] = 
	{
		[1] = 
		{
			["poiIndex"] = 26,
			["nodeIndex"] = 1,
		},
		[2] = 
		{
			["poiIndex"] = 27,
			["nodeIndex"] = 2,
		},
		[3] = 
		{
			["poiIndex"] = 28,
			["nodeIndex"] = 3,
		},
		[4] = 
		{
			["poiIndex"] = 29,
			["nodeIndex"] = 4,
		},
		[5] = 
		{
			["poiIndex"] = 30,
			["nodeIndex"] = 5,
		},
		[6] = 
		{
			["poiIndex"] = 31,
			["nodeIndex"] = 6,
		},
		[7] = 
		{
			["poiIndex"] = 32,
			["nodeIndex"] = 7,
		},
		[8] = 
		{
			["poiIndex"] = 33,
			["nodeIndex"] = 8,
		},
		[9] = 
		{
			["poiIndex"] = 34,
			["nodeIndex"] = 20,
		},
		[10] = 
		{
			["poiIndex"] = 35,
			["nodeIndex"] = 62,
		},
		[11] = 
		{
			["poiIndex"] = 36,
			["nodeIndex"] = 64,
		},
		[12] = 
		{
			["poiIndex"] = 42,
			["nodeIndex"] = 193,
		},
		[13] = 
		{
			["poiIndex"] = 46,
			["nodeIndex"] = 210,
		},
		[14] = 
		{
			["poiIndex"] = 63,
			["nodeIndex"] = 216,
		},
	},
	[100] = 
	{
		[1] = 
		{
			["poiIndex"] = 1,
			["nodeIndex"] = 215,
		},
	},
	[5] = 
	{
		[1] = 
		{
			["poiIndex"] = 17,
			["nodeIndex"] = 190,
		},
		[2] = 
		{
			["poiIndex"] = 18,
			["nodeIndex"] = 9,
		},
		[3] = 
		{
			["poiIndex"] = 19,
			["nodeIndex"] = 10,
		},
		[4] = 
		{
			["poiIndex"] = 20,
			["nodeIndex"] = 11,
		},
		[5] = 
		{
			["poiIndex"] = 22,
			["nodeIndex"] = 12,
		},
		[6] = 
		{
			["poiIndex"] = 23,
			["nodeIndex"] = 13,
		},
		[7] = 
		{
			["poiIndex"] = 24,
			["nodeIndex"] = 82,
		},
		[8] = 
		{
			["poiIndex"] = 25,
			["nodeIndex"] = 83,
		},
		[9] = 
		{
			["poiIndex"] = 26,
			["nodeIndex"] = 84,
		},
		[10] = 
		{
			["poiIndex"] = 27,
			["nodeIndex"] = 55,
		},
		[11] = 
		{
			["poiIndex"] = 37,
			["nodeIndex"] = 86,
		},
		[12] = 
		{
			["poiIndex"] = 41,
			["nodeIndex"] = 208,
		},
	},
	[38] = 
	{
		[1] = 
		{
			["poiIndex"] = 52,
			["nodeIndex"] = 170,
		},
		[2] = 
		{
			["poiIndex"] = 53,
			["nodeIndex"] = 199,
		},
		[3] = 
		{
			["poiIndex"] = 54,
			["nodeIndex"] = 200,
		},
		[4] = 
		{
			["poiIndex"] = 55,
			["nodeIndex"] = 201,
		},
		[5] = 
		{
			["poiIndex"] = 56,
			["nodeIndex"] = 202,
		},
		[6] = 
		{
			["poiIndex"] = 57,
			["nodeIndex"] = 203,
		},
	},
	[295] = 
	{
		[1] = 
		{
			["poiIndex"] = 5,
			["nodeIndex"] = 141,
		},
		[2] = 
		{
			["poiIndex"] = 6,
			["nodeIndex"] = 142,
		},
	},
	[9] = 
	{
		[1] = 
		{
			["poiIndex"] = 20,
			["nodeIndex"] = 65,
		},
		[2] = 
		{
			["poiIndex"] = 21,
			["nodeIndex"] = 66,
		},
		[3] = 
		{
			["poiIndex"] = 22,
			["nodeIndex"] = 41,
		},
		[4] = 
		{
			["poiIndex"] = 23,
			["nodeIndex"] = 67,
		},
		[5] = 
		{
			["poiIndex"] = 24,
			["nodeIndex"] = 68,
		},
		[6] = 
		{
			["poiIndex"] = 25,
			["nodeIndex"] = 71,
		},
		[7] = 
		{
			["poiIndex"] = 26,
			["nodeIndex"] = 72,
		},
		[8] = 
		{
			["poiIndex"] = 27,
			["nodeIndex"] = 73,
		},
		[9] = 
		{
			["poiIndex"] = 28,
			["nodeIndex"] = 74,
		},
		[10] = 
		{
			["poiIndex"] = 29,
			["nodeIndex"] = 75,
		},
		[11] = 
		{
			["poiIndex"] = 30,
			["nodeIndex"] = 76,
		},
		[12] = 
		{
			["poiIndex"] = 31,
			["nodeIndex"] = 77,
		},
		[13] = 
		{
			["poiIndex"] = 34,
			["nodeIndex"] = 98,
		},
		[14] = 
		{
			["poiIndex"] = 39,
			["nodeIndex"] = 69,
		},
		[15] = 
		{
			["poiIndex"] = 40,
			["nodeIndex"] = 108,
		},
		[16] = 
		{
			["poiIndex"] = 46,
			["nodeIndex"] = 212,
		},
	},
	[11] = 
	{
		[1] = 
		{
			["poiIndex"] = 21,
			["nodeIndex"] = 198,
		},
		[2] = 
		{
			["poiIndex"] = 22,
			["nodeIndex"] = 24,
		},
		[3] = 
		{
			["poiIndex"] = 23,
			["nodeIndex"] = 25,
		},
		[4] = 
		{
			["poiIndex"] = 24,
			["nodeIndex"] = 26,
		},
		[5] = 
		{
			["poiIndex"] = 25,
			["nodeIndex"] = 27,
		},
		[6] = 
		{
			["poiIndex"] = 26,
			["nodeIndex"] = 28,
		},
		[7] = 
		{
			["poiIndex"] = 27,
			["nodeIndex"] = 29,
		},
		[8] = 
		{
			["poiIndex"] = 28,
			["nodeIndex"] = 30,
		},
		[9] = 
		{
			["poiIndex"] = 29,
			["nodeIndex"] = 32,
		},
		[10] = 
		{
			["poiIndex"] = 30,
			["nodeIndex"] = 79,
		},
		[11] = 
		{
			["poiIndex"] = 31,
			["nodeIndex"] = 80,
		},
		[12] = 
		{
			["poiIndex"] = 32,
			["nodeIndex"] = 81,
		},
		[13] = 
		{
			["poiIndex"] = 43,
			["nodeIndex"] = 205,
		},
	},
	[12] = 
	{
		[1] = 
		{
			["poiIndex"] = 2,
			["nodeIndex"] = 101,
		},
		[2] = 
		{
			["poiIndex"] = 3,
			["nodeIndex"] = 99,
		},
		[3] = 
		{
			["poiIndex"] = 4,
			["nodeIndex"] = 102,
		},
		[4] = 
		{
			["poiIndex"] = 5,
			["nodeIndex"] = 100,
		},
		[5] = 
		{
			["poiIndex"] = 6,
			["nodeIndex"] = 104,
		},
		[6] = 
		{
			["poiIndex"] = 7,
			["nodeIndex"] = 105,
		},
		[7] = 
		{
			["poiIndex"] = 8,
			["nodeIndex"] = 106,
		},
		[8] = 
		{
			["poiIndex"] = 9,
			["nodeIndex"] = 103,
		},
		[9] = 
		{
			["poiIndex"] = 10,
			["nodeIndex"] = 107,
		},
		[10] = 
		{
			["poiIndex"] = 41,
			["nodeIndex"] = 188,
		},
	},
	[110] = 
	{
		[1] = 
		{
			["poiIndex"] = 3,
			["nodeIndex"] = 172,
		},
	},
	[111] = 
	{
		[1] = 
		{
			["poiIndex"] = 2,
			["nodeIndex"] = 173,
		},
		[2] = 
		{
			["poiIndex"] = 3,
			["nodeIndex"] = 125,
		},
		[3] = 
		{
			["poiIndex"] = 4,
			["nodeIndex"] = 126,
		},
	},
	[16] = 
	{
		[1] = 
		{
			["poiIndex"] = 14,
			["nodeIndex"] = 87,
		},
		[2] = 
		{
			["poiIndex"] = 15,
			["nodeIndex"] = 88,
		},
		[3] = 
		{
			["poiIndex"] = 16,
			["nodeIndex"] = 89,
		},
		[4] = 
		{
			["poiIndex"] = 17,
			["nodeIndex"] = 90,
		},
		[5] = 
		{
			["poiIndex"] = 18,
			["nodeIndex"] = 91,
		},
		[6] = 
		{
			["poiIndex"] = 19,
			["nodeIndex"] = 92,
		},
		[7] = 
		{
			["poiIndex"] = 20,
			["nodeIndex"] = 93,
		},
		[8] = 
		{
			["poiIndex"] = 21,
			["nodeIndex"] = 94,
		},
		[9] = 
		{
			["poiIndex"] = 22,
			["nodeIndex"] = 95,
		},
		[10] = 
		{
			["poiIndex"] = 23,
			["nodeIndex"] = 96,
		},
		[11] = 
		{
			["poiIndex"] = 24,
			["nodeIndex"] = 97,
		},
		[12] = 
		{
			["poiIndex"] = 41,
			["nodeIndex"] = 195,
		},
	},
	[17] = 
	{
		[1] = 
		{
			["poiIndex"] = 14,
			["nodeIndex"] = 109,
		},
		[2] = 
		{
			["poiIndex"] = 15,
			["nodeIndex"] = 110,
		},
		[3] = 
		{
			["poiIndex"] = 16,
			["nodeIndex"] = 111,
		},
		[4] = 
		{
			["poiIndex"] = 17,
			["nodeIndex"] = 112,
		},
		[5] = 
		{
			["poiIndex"] = 23,
			["nodeIndex"] = 113,
		},
		[6] = 
		{
			["poiIndex"] = 24,
			["nodeIndex"] = 114,
		},
		[7] = 
		{
			["poiIndex"] = 25,
			["nodeIndex"] = 115,
		},
		[8] = 
		{
			["poiIndex"] = 26,
			["nodeIndex"] = 116,
		},
		[9] = 
		{
			["poiIndex"] = 27,
			["nodeIndex"] = 117,
		},
		[10] = 
		{
			["poiIndex"] = 28,
			["nodeIndex"] = 118,
		},
		[11] = 
		{
			["poiIndex"] = 29,
			["nodeIndex"] = 119,
		},
		[12] = 
		{
			["poiIndex"] = 30,
			["nodeIndex"] = 120,
		},
		[13] = 
		{
			["poiIndex"] = 42,
			["nodeIndex"] = 187,
		},
	},
	[18] = 
	{
		[1] = 
		{
			["poiIndex"] = 17,
			["nodeIndex"] = 42,
		},
		[2] = 
		{
			["poiIndex"] = 18,
			["nodeIndex"] = 43,
		},
		[3] = 
		{
			["poiIndex"] = 19,
			["nodeIndex"] = 44,
		},
		[4] = 
		{
			["poiIndex"] = 20,
			["nodeIndex"] = 45,
		},
		[5] = 
		{
			["poiIndex"] = 21,
			["nodeIndex"] = 46,
		},
		[6] = 
		{
			["poiIndex"] = 29,
			["nodeIndex"] = 57,
		},
		[7] = 
		{
			["poiIndex"] = 30,
			["nodeIndex"] = 58,
		},
		[8] = 
		{
			["poiIndex"] = 31,
			["nodeIndex"] = 59,
		},
		[9] = 
		{
			["poiIndex"] = 32,
			["nodeIndex"] = 137,
		},
		[10] = 
		{
			["poiIndex"] = 34,
			["nodeIndex"] = 60,
		},
		[11] = 
		{
			["poiIndex"] = 35,
			["nodeIndex"] = 61,
		},
		[12] = 
		{
			["poiIndex"] = 42,
			["nodeIndex"] = 196,
		},
		[13] = 
		{
			["poiIndex"] = 43,
			["nodeIndex"] = 155,
		},
	},
	[19] = 
	{
		[1] = 
		{
			["poiIndex"] = 17,
			["nodeIndex"] = 147,
		},
		[2] = 
		{
			["poiIndex"] = 18,
			["nodeIndex"] = 143,
		},
		[3] = 
		{
			["poiIndex"] = 19,
			["nodeIndex"] = 148,
		},
		[4] = 
		{
			["poiIndex"] = 20,
			["nodeIndex"] = 149,
		},
		[5] = 
		{
			["poiIndex"] = 21,
			["nodeIndex"] = 150,
		},
		[6] = 
		{
			["poiIndex"] = 22,
			["nodeIndex"] = 151,
		},
		[7] = 
		{
			["poiIndex"] = 23,
			["nodeIndex"] = 152,
		},
		[8] = 
		{
			["poiIndex"] = 24,
			["nodeIndex"] = 153,
		},
		[9] = 
		{
			["poiIndex"] = 25,
			["nodeIndex"] = 154,
		},
		[10] = 
		{
			["poiIndex"] = 39,
			["nodeIndex"] = 197,
		},
	},
	[180] = 
	{
		[1] = 
		{
			["poiIndex"] = 29,
			["nodeIndex"] = 185,
		},
		[2] = 
		{
			["poiIndex"] = 30,
			["nodeIndex"] = 144,
		},
		[3] = 
		{
			["poiIndex"] = 31,
			["nodeIndex"] = 156,
		},
		[4] = 
		{
			["poiIndex"] = 32,
			["nodeIndex"] = 157,
		},
		[5] = 
		{
			["poiIndex"] = 34,
			["nodeIndex"] = 158,
		},
		[6] = 
		{
			["poiIndex"] = 35,
			["nodeIndex"] = 159,
		},
		[7] = 
		{
			["poiIndex"] = 36,
			["nodeIndex"] = 160,
		},
		[8] = 
		{
			["poiIndex"] = 37,
			["nodeIndex"] = 161,
		},
		[9] = 
		{
			["poiIndex"] = 38,
			["nodeIndex"] = 162,
		},
		[10] = 
		{
			["poiIndex"] = 39,
			["nodeIndex"] = 163,
		},
	},
	[181] = 
	{
		[1] = 
		{
			["poiIndex"] = 8,
			["nodeIndex"] = 191,
		},
		[2] = 
		{
			["poiIndex"] = 15,
			["nodeIndex"] = 214,
		},
		[3] = 
		{
			["poiIndex"] = 16,
			["nodeIndex"] = 164,
		},
		[4] = 
		{
			["poiIndex"] = 17,
			["nodeIndex"] = 21,
		},
		[5] = 
		{
			["poiIndex"] = 18,
			["nodeIndex"] = 165,
		},
		[6] = 
		{
			["poiIndex"] = 19,
			["nodeIndex"] = 166,
		},
		[7] = 
		{
			["poiIndex"] = 20,
			["nodeIndex"] = 167,
		},
		[8] = 
		{
			["poiIndex"] = 21,
			["nodeIndex"] = 168,
		},
		[9] = 
		{
			["poiIndex"] = 22,
			["nodeIndex"] = 169,
		},
		[10] = 
		{
			["poiIndex"] = 40,
			["nodeIndex"] = 207,
		},
		[11] = 
		{
			["poiIndex"] = 41,
			["nodeIndex"] = 213,
		},
	},
	[15] = 
	{
		[1] = 
		{
			["poiIndex"] = 19,
			["nodeIndex"] = 33,
		},
		[2] = 
		{
			["poiIndex"] = 20,
			["nodeIndex"] = 34,
		},
		[3] = 
		{
			["poiIndex"] = 21,
			["nodeIndex"] = 35,
		},
		[4] = 
		{
			["poiIndex"] = 22,
			["nodeIndex"] = 36,
		},
		[5] = 
		{
			["poiIndex"] = 23,
			["nodeIndex"] = 37,
		},
		[6] = 
		{
			["poiIndex"] = 24,
			["nodeIndex"] = 38,
		},
		[7] = 
		{
			["poiIndex"] = 25,
			["nodeIndex"] = 39,
		},
		[8] = 
		{
			["poiIndex"] = 26,
			["nodeIndex"] = 40,
		},
		[9] = 
		{
			["poiIndex"] = 27,
			["nodeIndex"] = 63,
		},
		[10] = 
		{
			["poiIndex"] = 36,
			["nodeIndex"] = 186,
		},
		[11] = 
		{
			["poiIndex"] = 40,
			["nodeIndex"] = 204,
		},
		[12] = 
		{
			["poiIndex"] = 41,
			["nodeIndex"] = 206,
		},
	},
	[294] = 
	{
		[1] = 
		{
			["poiIndex"] = 3,
			["nodeIndex"] = 181,
		},
		[2] = 
		{
			["poiIndex"] = 4,
			["nodeIndex"] = 182,
		},
		[3] = 
		{
			["poiIndex"] = 5,
			["nodeIndex"] = 183,
		},
	},
	[155] = 
	{
		[1] = 
		{
			["poiIndex"] = 5,
			["nodeIndex"] = 128,
		},
		[2] = 
		{
			["poiIndex"] = 6,
			["nodeIndex"] = 129,
		},
		[3] = 
		{
			["poiIndex"] = 7,
			["nodeIndex"] = 130,
		},
		[4] = 
		{
			["poiIndex"] = 8,
			["nodeIndex"] = 131,
		},
		[5] = 
		{
			["poiIndex"] = 9,
			["nodeIndex"] = 132,
		},
		[6] = 
		{
			["poiIndex"] = 10,
			["nodeIndex"] = 133,
		},
		[7] = 
		{
			["poiIndex"] = 11,
			["nodeIndex"] = 134,
		},
		[8] = 
		{
			["poiIndex"] = 12,
			["nodeIndex"] = 135,
		},
		[9] = 
		{
			["poiIndex"] = 13,
			["nodeIndex"] = 136,
		},
		[10] = 
		{
			["poiIndex"] = 14,
			["nodeIndex"] = 139,
		},
		[11] = 
		{
			["poiIndex"] = 15,
			["nodeIndex"] = 140,
		},
		[12] = 
		{
			["poiIndex"] = 27,
			["nodeIndex"] = 145,
		},
		[13] = 
		{
			["poiIndex"] = 29,
			["nodeIndex"] = 146,
		},
		[14] = 
		{
			["poiIndex"] = 39,
			["nodeIndex"] = 184,
		},
	},
	[179] = 
	{
		[1] = 
		{
			["poiIndex"] = 20,
			["nodeIndex"] = 177,
		},
		[2] = 
		{
			["poiIndex"] = 23,
			["nodeIndex"] = 178,
		},
		[3] = 
		{
			["poiIndex"] = 24,
			["nodeIndex"] = 174,
		},
		[4] = 
		{
			["poiIndex"] = 25,
			["nodeIndex"] = 175,
		},
		[5] = 
		{
			["poiIndex"] = 26,
			["nodeIndex"] = 176,
		},
		[6] = 
		{
			["poiIndex"] = 27,
			["nodeIndex"] = 121,
		},
		[7] = 
		{
			["poiIndex"] = 28,
			["nodeIndex"] = 122,
		},
		[8] = 
		{
			["poiIndex"] = 29,
			["nodeIndex"] = 123,
		},
		[9] = 
		{
			["poiIndex"] = 30,
			["nodeIndex"] = 124,
		},
		[10] = 
		{
			["poiIndex"] = 33,
			["nodeIndex"] = 127,
		},
		[11] = 
		{
			["poiIndex"] = 41,
			["nodeIndex"] = 194,
		},
		[12] = 
		{
			["poiIndex"] = 42,
			["nodeIndex"] = 211,
		},
	},
	[20] = 
	{
		[1] = 
		{
			["poiIndex"] = 20,
			["nodeIndex"] = 47,
		},
		[2] = 
		{
			["poiIndex"] = 21,
			["nodeIndex"] = 48,
		},
		[3] = 
		{
			["poiIndex"] = 22,
			["nodeIndex"] = 49,
		},
		[4] = 
		{
			["poiIndex"] = 23,
			["nodeIndex"] = 171,
		},
		[5] = 
		{
			["poiIndex"] = 24,
			["nodeIndex"] = 50,
		},
		[6] = 
		{
			["poiIndex"] = 26,
			["nodeIndex"] = 51,
		},
		[7] = 
		{
			["poiIndex"] = 27,
			["nodeIndex"] = 52,
		},
		[8] = 
		{
			["poiIndex"] = 28,
			["nodeIndex"] = 53,
		},
		[9] = 
		{
			["poiIndex"] = 30,
			["nodeIndex"] = 78,
		},
		[10] = 
		{
			["poiIndex"] = 31,
			["nodeIndex"] = 85,
		},
		[11] = 
		{
			["poiIndex"] = 39,
			["nodeIndex"] = 192,
		},
	},
	[4] = 
	{
		[1] = 
		{
			["poiIndex"] = 20,
			["nodeIndex"] = 189,
		},
		[2] = 
		{
			["poiIndex"] = 22,
			["nodeIndex"] = 14,
		},
		[3] = 
		{
			["poiIndex"] = 23,
			["nodeIndex"] = 15,
		},
		[4] = 
		{
			["poiIndex"] = 24,
			["nodeIndex"] = 16,
		},
		[5] = 
		{
			["poiIndex"] = 25,
			["nodeIndex"] = 22,
		},
		[6] = 
		{
			["poiIndex"] = 26,
			["nodeIndex"] = 23,
		},
		[7] = 
		{
			["poiIndex"] = 27,
			["nodeIndex"] = 18,
		},
		[8] = 
		{
			["poiIndex"] = 28,
			["nodeIndex"] = 19,
		},
		[9] = 
		{
			["poiIndex"] = 35,
			["nodeIndex"] = 31,
		},
		[10] = 
		{
			["poiIndex"] = 42,
			["nodeIndex"] = 56,
		},
		[11] = 
		{
			["poiIndex"] = 43,
			["nodeIndex"] = 17,
		},
	},
	[293] = 
	{
		[1] = 
		{
			["poiIndex"] = 4,
			["nodeIndex"] = 138,
		},
		[2] = 
		{
			["poiIndex"] = 6,
			["nodeIndex"] = 179,
		},
		[3] = 
		{
			["poiIndex"] = 7,
			["nodeIndex"] = 180,
		},
	}
}
-- cache for formatted wayshrine names
local _nodeNameCache = {}

local function GetNodeName(nodeIndex,name)
	local localeName = _nodeNameCache[nodeIndex]
	
	if localeName == nil then 
		localeName = Utils.FormatStringCurrentLanguage(name)
		_nodeNameCache[nodeIndex] = localeName
	end 
	
	return localeName
end 

local function GetNodesByZoneIndex(zoneIndex)
	if zoneIndex ~= nil then 
		local nodes = _zoneNodeLookup[zoneIndex]
		if nodes ~= nil then 
			return Utils.copy(nodes)
		end
	end 
	return {}
end



local function GetNodeInfo(nodeIndex)
	if nodeIndex == nil then return nil end 
	
	local known,name,normalizedX, normalizedY, textureName ,textureName,poiType,isShown = GetFastTravelNodeInfo(nodeIndex)
	
	name = GetNodeName(nodeIndex,name)
	
	return known,name,normalizedX, normalizedY, textureName ,textureName,poiType,isShown
end 

local d = Data

d.GetNodesByZoneIndex = GetNodesByZoneIndex
d.GetNodeInfo = GetNodeInfo

FasterTravel.Wayshrine.Data = d  